export const paymentData = [
  {
    srNo: 1,
    orderedDate: "01 Jul 2026",
    selectedPlan: "Premium",
    orgName: "ABC Technologies",
    department: "IT",
    name: "Rahul Sharma",
    total: 4999,
    gstNo: "27ABCDE1234F1Z5",
    paymentStatus: "Paid",
  },
  {
    srNo: 2,
    orderedDate: "02 Jul 2026",
    selectedPlan: "Standard",
    orgName: "TechNova Pvt Ltd",
    department: "HR",
    name: "Priya Verma",
    total: 2999,
    gstNo: "27PQRSX5678K1Z2",
    paymentStatus: "Pending",
  },
  {
    srNo: 3,
    orderedDate: "03 Jul 2026",
    selectedPlan: "Basic",
    orgName: "Event Hub",
    department: "Marketing",
    name: "Amit Kumar",
    total: 1999,
    gstNo: "27LMNOP4321Q1Z8",
    paymentStatus: "Paid",
  },
  {
    srNo: 4,
    orderedDate: "04 Jul 2026",
    selectedPlan: "Premium",
    orgName: "Future Soft",
    department: "Finance",
    name: "Neha Singh",
    total: 4999,
    gstNo: "27XYZAB9876T1Z4",
    paymentStatus: "Failed",
  },
  {
    srNo: 5,
    orderedDate: "05 Jul 2026",
    selectedPlan: "Enterprise",
    orgName: "Creative Minds",
    department: "Admin",
    name: "Karan Patel",
    total: 9999,
    gstNo: "27QWER1234P1Z6",
    paymentStatus: "Paid",
  },
  {
    srNo: 6,
    orderedDate: "06 Jul 2026",
    selectedPlan: "Standard",
    orgName: "Vision IT",
    department: "Support",
    name: "Sneha Joshi",
    total: 2999,
    gstNo: "27GHJK5678L1Z9",
    paymentStatus: "Pending",
  },
  {
    srNo: 7,
    orderedDate: "07 Jul 2026",
    selectedPlan: "Basic",
    orgName: "Skyline Solutions",
    department: "Sales",
    name: "Rohan Gupta",
    total: 1999,
    gstNo: "27ZXCV6789A1Z3",
    paymentStatus: "Paid",
  },
  {
    srNo: 8,
    orderedDate: "08 Jul 2026",
    selectedPlan: "Premium",
    orgName: "Innovate Pvt Ltd",
    department: "IT",
    name: "Pooja Mehta",
    total: 4999,
    gstNo: "27ASDF1234D1Z1",
    paymentStatus: "Paid",
  },
  {
    srNo: 9,
    orderedDate: "09 Jul 2026",
    selectedPlan: "Enterprise",
    orgName: "Global Events",
    department: "Operations",
    name: "Vikas Jain",
    total: 9999,
    gstNo: "27LKJH8765M1Z7",
    paymentStatus: "Pending",
  },
  {
    srNo: 10,
    orderedDate: "10 Jul 2026",
    selectedPlan: "Standard",
    orgName: "NextGen Solutions",
    department: "HR",
    name: "Anjali Deshmukh",
    total: 2999,
    gstNo: "27MNBV4567R1Z0",
    paymentStatus: "Paid",
  },
];